name: Secrets and Env vars

env: 
  APP_ENV: production

  
on: 
  workflow_dispatch:



jobs:
  secret_manager:
    runs-on: ubuntu-latest

    steps:
    - name: Print workflow env
      run: echo $APP_ENV

    - name: Print Secrets
      env:
        MY_SECRET: ${{ secrets.MY_SECRET}}
      run: echo $MY_SECRET
    
    - name: Print Step var
      env:
        STEP_VAR: hello
      run: echo $STEP_VAR



