name: sarif linting

on:
    workflow_dispatch:
      
jobs:
    sarif_linting:
        permissions:
            security-events: write
            actions: read
            contents: read
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4
        
        -   name: Install dependancies
            run: pip install bandit bandit-sarif-formatter

        -   name: Output SARIF directly
            run: bandit -r . -f sarif -o bandit.sarif || true
        
        -   name: Upload SARIF to security tab
            uses: github/codeql-action/upload-sarif@v3
            with:
                sarif_file: bandit.sarif